#+STARTUP: content
#+STARTUP: indent

* Information about the project
Implementation of a atmega-8 clone in VHDL, using emacs & vivado
* Current state of the project
The semester is finished, and so is the project... or almost. Thought the simulation works "flawlessly" (cf presentation pdf), the implementation on fpga is not working correctly. Some latches are prpobably involved.

I had to finished the semester one month earlier so I lacked time for implementing 3 or 4 level pipelines, tweaking the synthesis so the frequency of the processor could be increased...
* Things learned in that project
** switch to Emacs
Having to use emacs after having been converted to vim wasn't so easy at first,
but I think that I have now adopted Emacs, maybe even for good ! Well, a
totally Vim flavored emacs (thank you my dear Evil !) but still, Emacs.
** Git !
 - intensive usage of git during the project
 - seeing the utility of branches, stashes and regular commits even for a solo
 project
** VHDL
Obviously, a lot of VHDL was learned with this project !
*** Software vs Hardware engineering
When developping on hardware, always have in mind how the hardware will be
generated and that means trying to stick to templates and do NOT try to tweak
them. Tweaks should go arouuuuund !
** General programming skills
*** New features developpement cycle
This project is making me realise how much the cycle =implement -> test ->
debug -> commit= is important and efficient. I still have much trouble applying
it for big new features.

For exemple : adding the instructions LD/ST. A lot of changes had to be done
before a actual test could be done (especially the changes in top_level.vhd
that always demands a lot of attention).

A solution could be to right a short test-bench in order to be able to test the
specific developped component.
